dist: bionic
language: python
git:
  depth: false
python:
  - "3.7"
install:
  - pip install -r requirements.txt
before_script:
  - sudo git config --system --replace-all user.email "$GIT_AUTHOR_EMAIL"
  - sudo git config --system --replace-all user.name "$GIT_AUTHOR_NAME"
script:
  - ./update.py
